version: "3"
dotenv: [".env"]
output: prefixed

vars:
  OS_DIST:
    sh: |
      [[ -f /etc/os-release ]] && cat /etc/os-release | grep -iE "^id=" | head -1 | cut -d= -f2 | tr '[:upper:]' '[:lower:]' || echo "nil"

  USER_HOME:
    sh: |
      echo "$HOME"

  BIN:
    sh: |
      echo "$HOME/bin"

  LOCAL_TMP:
    sh: |
      echo "$(pwd)/.tasks_tmp"

tasks:

  default:
    prefix: "..."
    cmds:
      - task -l
    silent: true

  curl:check:
    preconditions:
      - sh: command -v curl
        msg: "'curl' must be installed in order to run this task"

  basics:install:
    desc: Installs all the basic software I use regularly
    deps: [curl:check]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - task: yq:install
      - task: jq:install
      - task: git:install
      - task: go:install
      - task: rust:install
      - task: docker:install
      - task: kubectl:install
      - task: glab:install
      - task: eza:install
      - task: zsh:install
      - task: precommit:install
      - task: cleanup

  configure:
    run: once
    desc: Configures a local temp environment for easy cleanup
    cmds:
      - mkdir -pv {{.LOCAL_TMP}}
    silent: true

  bin:install:
    run: once
    desc: Creates the user home binaries folder
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - mkdir -pv {{.BIN}}
    silent: true

  git:install:
    run: once
    desc: Installs 'git'
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ "{{OS}}" == "linux" ]]; then
          if [[ "{{.OS_DIST}}" == "debian" || "{{.OS_DIST}}" == "ubuntu" ]]; then
            [[ $(command -v git) ]] || sudo apt install -y git
          fi
        elif [[ "{{OS}}" == "darwin" ]]; then
          [[ $(command -v git) ]] || brew install git
        fi
    silent: true

  azure:install:
    run: once
    desc: Installs 'azure-cli'
    deps: [configure, curl:check]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ "{{OS}}" == "linux" ]]; then
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        else
          curl -sL https://aka.ms/InstallAzureCli | sudo bash
        fi
    silent: true

  precommit:install:
    run: once
    desc: Installs 'pre-commit'
    deps: [configure, curl:check]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ "{{OS}}" == "darwin" ]]; then
          brew install pre-commit
        elif [[ "{{OS}}" == "linux" ]]; then
          if [[ "{{.OS_DIST}}" == "debian" || "{{.OS_DIST}}" == "ubuntu" ]]; then
            echo "[WARNING] there appears to be no automated way to install pre-commit on {{OS}}. install it manually from https://pre-commit.com/#install"
          fi
        fi
    silent: true

  rust:install:
    run: once
    desc: Installs the 'rust' toolchain
    deps: [configure, curl:check]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sudo sh -s -- -y
    silent: true

  go:download:
    run: once
    desc: Downloads 'go' installation files
    deps: [configure, curl:check]
    vars:
      GO_VERSION: 1.22.4
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ "{{OS}}" == "linux" ]]; then
          [[ $(command -v go) ]] || curl -LO https://go.dev/dl/go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.tar.gz
        elif [[ "{{OS}}" == "darwin" ]]; then
          [[ $(command -v go) ]] || curl -LO https://go.dev/dl/go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.pkg
        fi
    silent: true

  go:install:
    run: once
    desc: Installs 'go'
    deps: [configure, go:download]
    vars:
      GO_VERSION: 1.22.4
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ "{{OS}}" == "linux" ]]; then
          [[ $(command -v go) ]] || (rm -rf {{.USER_HOME}}/go && tar -C {{.USER_HOME}} -zxvf go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.tar.gz && rm -f go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.tar.gz)
        elif [[ "{{OS}}" == "darwin" ]]; then
          [[ $(command -v go) ]] || sudo installer -pkg go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.pkg -target / && rm -f go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.pkg
        fi
    silent: true

  jq:install:
    run: once
    desc: Installs 'jq'
    deps: [bin:install]
    cmds:
      - >
        if [[ "{{OS}}" == "linux" ]]; then
          curl -sSLo {{.BIN}}/jq https://github.com/stedolan/jq/releases/download/jq-{{.VERSION}}/jq-linux64 && chmod 0750 {{.BIN}}/jq
        elif [[ "{{OS}}" == "darwin" ]]; then
          brew install jq
        fi
    silent: true

  docker:install:
    run: once
    desc: Installs 'docker'
    deps: [configure, curl:check]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ "{{OS}}" == "linux" ]]; then
          if [[ "{{.OS_DIST}}" == "ubuntu" || "{{.OS_DIST}}" == "debian" ]]; then
            sudo apt-get update
            sudo apt-get install -y ca-certificates gnupg lsb-release
            sudo mkdir -m 0755 -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          fi
        else
          echo "[WARNING] Will not download docker on {{OS}} ... please download docker desktop from their website: https://www.docker.com/products/docker-desktop/"
        fi
    silent: true

  kubectl:download:
    run: once
    desc: Downloads 'kubectl' installation files
    deps: [configure, curl:check]
    dir: "{{.LOCAL_TMP}}"
    vars:
      VERSION:
        sh: curl -Ls https://dl.k8s.io/release/stable.txt
    cmds:
      - curl -LO "https://dl.k8s.io/release/{{.VERSION}}/bin/{{OS}}/{{ARCH}}/kubectl"
      - chmod 0755 kubectl
    silent: true

  kubectl:install:
    run: once
    desc: Installs 'kubectl'
    deps: [configure, bin:install, kubectl:download]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - mv kubectl {{.BIN}}/kubectl
    silent: true

  k9s:download:
    run: once
    desc: Downloads 'k9s' installation files
    deps: [configure, jq:install, curl:check]
    dir: "{{.LOCAL_TMP}}"
    vars:
      VERSION:
        sh: curl -s https://api.github.com/repos/derailed/k9s/releases/latest | jq -r .tag_name
    cmds:
      - curl -L https://github.com/derailed/k9s/releases/download/{{.VERSION}}/k9s_{{OS}}_{{ARCH}}.tar.gz -o k9s_{{OS}}_{{ARCH}}.tar.gz
      - tar -zxf k9s_{{OS}}_{{ARCH}}.tar.gz k9s
      - rm -f k9s_{{OS}}_{{ARCH}}.tar.gz
    silent: true

  k9s:install:
    run: once
    desc: Installs 'k9s'
    deps: [bin:install, k9s:download]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - mv k9s {{.BIN}}/k9s
    silent: true

  terraform:download:
    run: once
    desc: Downloads 'terraform' installation files
    deps: [configure, curl:check]
    vars:
      TERRAFORM_VERSION: "1.4.2"
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - curl -LO https://releases.hashicorp.com/terraform/{{.TERRAFORM_VERSION}}/terraform_{{.TERRAFORM_VERSION}}_{{OS}}_{{ARCH}}.zip
      - unzip terraform_{{.TERRAFORM_VERSION}}_{{OS}}_{{ARCH}}.zip && rm -f terraform_{{.TERRAFORM_VERSION}}_{{OS}}_{{ARCH}}.zip
    silent: true

  terraform:install:
    run: once
    desc: Install 'terraform'
    deps: [bin:install, terraform:download]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - mv terraform {{.BIN}}/terraform
    silent: true

  terraform-docs:download:
    run: once
    desc: Downloads 'terraform-docs' installation files
    deps: [configure, curl:check]
    dir: "{{.LOCAL_TMP}}"
    vars:
      VERSION: v0.16.0
    cmds:
      - curl -LO https://terraform-docs.io/dl/{{.VERSION}}/terraform-docs-{{.VERSION}}-{{OS}}-{{ARCH}}.tar.gz
      - tar -zxf terraform-docs-{{.VERSION}}-{{OS}}-{{ARCH}}.tar.gz terraform-docs
      - rm -f terraform-docs-{{.VERSION}}-{{OS}}-{{ARCH}}.tar.gz
    silent: true

  terraform-docs:install:
    run: once
    desc: Installs 'terraform-docs'
    deps: [bin:install, terraform-docs:download]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - mv terraform-docs {{.BIN}}/terraform-docs
    silent: true

  helm:download:
    run: once
    desc: Downloads 'helm' installation files
    deps: [configure, jq:install, curl:check]
    dir: "{{.LOCAL_TMP}}"
    vars:
      VERSION:
        sh: curl -s https://api.github.com/repos/helm/helm/releases/latest | jq -r .tag_name
    cmds:
      - curl -LO https://get.helm.sh/helm-{{.VERSION}}-{{OS}}-{{ARCH}}.tar.gz
      - tar -zxf helm-{{.VERSION}}-{{OS}}-{{ARCH}}.tar.gz && rm -f helm-{{.VERSION}}-{{OS}}-{{ARCH}}.tar.gz
    silent: true

  helm:install:
    run: once
    desc: Installs 'helm'
    deps: [bin:install, helm:download]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - mv {{OS}}-{{ARCH}}/helm {{.BIN}}/helm && rm -rf {{OS}}-{{ARCH}}
    silent: true

  helm-docs:install:
    run: once
    desc: Installs 'helm-docs'
    deps: [configure, go:install]
    dir: "{{.LOCAL_TMP}}"
    vars:
      VERSION: v1.11.0
    cmds:
      - GO111MODULE=on go install github.com/norwoodj/helm-docs/cmd/helm-docs@{{.VERSION}}
    silent: true

  kwok:download:
    run: once
    desc: Download 'kwok' installation files
    deps: [configure, jq:install, go:install, curl:check]
    dir: "{{.LOCAL_TMP}}"
    vars:
      KWOK_REPO: kubernetes-sigs/kwok
      VERSION:
        sh: curl https://api.github.com/repos/{{.KWOK_REPO}}/releases/latest | jq -r '.tag_name'
    cmds:
      - curl -LO https://github.com/{{.KWOK_REPO}}/releases/download/{{.VERSION}}/kwokctl-{{OS}}-{{ARCH}}
      - chmod 0755 kwokctl-{{OS}}-{{ARCH}}
    silent: true

  kwok:install:
    run: once
    desc: Installs 'kwok'
    deps: [bin:install, kwok:download]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - mv kwokctl-{{OS}}-{{ARCH}} {{.BIN}}/kwokctl
    silent: true

  glab:download:
    run: once
    desc: Downloads 'glab' installation files
    deps: [configure, go:install, git:install]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ "{{OS}}" == "linux" ]]; then
          [[ $(command -v glab) ]] || git clone https://gitlab.com/gitlab-org/cli.git glab
        fi
    silent: true

  glab:install:
    run: once
    desc: Installs 'glab'
    preconditions:
      - sh: command -v make
        msg: "'make' must be installed in order to compile 'glab'"
    deps: [glab:download]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ ! $(command -v glab) ]]; then
          if [[ "{{OS}}" == "linux" ]]; then
            cd glab && PATH=$PATH:{{.USER_HOME}}/go/bin make install
          elif [[ "{{OS}}" == "darwin" ]]; then
            brew install glab
          fi
        fi
    silent: true

  code:install:
    run: once
    desc: Installs 'Visual Studio Code' and extensions
    deps: [configure]
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ ! $(command -v code) ]]; then
          if [[ "{{OS}}" == "linux" ]]; then
            if [[ {{.OS_DIST}} == "ubuntu" || {{.OS_DIST}} == "debian" ]]; then
              sudo apt install -y code
            fi
          elif [[ "{{OS}}" == "darwin" ]]; then
            brew install --cask visual-studio-code
          fi
        fi
      - >
        extensions=(
          hashicorp.terraform
          4ops.packer
          editorconfig.editorconfig
          monokai.theme-monokai-pro-vscode
          esbenp.prettier-vscode
          golang.go
          rust-lang.rust-analyzer
          redhat.ansible
          redhat.vscode-commons
          redhat.vscode-yaml
          asvetliakov.vscode-neovim
          yzhang.markdown-all-in-one
          oderwat.indent-rainbow
          sirtori.indenticator
          ms-kubernetes-tools.vscode-kubernetes-tools
          amazonwebservices.aws-toolkit-vscode
          aaron-bond.better-comments
          christian-kohler.path-intellisense
          jinliming2.vscode-go-template
          tamasfe.even-better-toml
          vue.volar
          wayou.vscode-todo-highlight
        )

        for extension in ${extensions[@]}; do
          code --force --install-extension $extension
        done
    silent: true

  yq:install:
    run: once
    desc: Downloads and Installs 'yq'
    deps: [bin:install]
    vars:
      YQ_VERSION: "v4.33.3"
    dir: "{{.BIN}}"
    cmds:
      - curl -sSLo yq https://github.com/mikefarah/yq/releases/download/{{.YQ_VERSION}}/yq_{{OS}}_{{ARCH}}
      - chmod 0755 yq
    silent: true

  zsh:install:
    run: once
    desc: Installs the ZSH shell
    cmds:
      - >
        if [[ ! $(command -v zsh) ]]; then
          if [[ "{{OS}}" == "linux" ]]; then
            if [[ "{{.OS_DIST}}" == "debian" ]]; then
              sudo apt-get update && sudo apt-get install -y zsh
            fi
          elif [[ "{{OS}}" == "darwin" ]]; then
            brew install zsh
          fi
        fi
    silent: true

  eza:install:
    run: once
    desc: Downloads and installs 'exa'
    deps: [bin:install]
    vars:
      EZA_VERSION: "v0.18.17"
    dir: "{{.BIN}}"
    cmds:
      - >
        if [[ "{{OS}}" == "darwin" ]]; then
          brew install eza
        else
          curl -sSLf https://github.com/eza-community/eza/releases/download/{{.EZA_VERSION}}/eza_x86_64-unknown-linux-gnu.tar.gz | tar -zx
          mv eza {{.BIN}}/eza && chmod 0750 {{.BIN}}/eza
          curl -sSLo $HOME/.zsh_completions/_eza https://raw.githubusercontent.com/eza-community/eza/main/completions/zsh/_eza
        fi
    silent: true

  oc:download:
    run: once
    desc: Downloads 'oc' and extracts its contents to {{.LOCAL_TMP}}
    deps: [configure]
    vars:
      OC_VERSION: "4.14.1"
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - curl -sSLo oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{.OC_VERSION}}/openshift-client-src.tar.gz
      - tar -zxf oc.tar.gz
    silent: true

  oc:install:
    run: once
    desc: Make and Installs OC (requires GCC)
    deps: [bin:install, oc:download, go:install]
    vars:
      OC_VERSION: "4.14.1"
    preconditions:
    - sh: command -v make
      msg: "'make' must be installed in order to compile 'oc'"
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ ! $(command -v oc) ]]; then
          if [[ "{{OS}}" == "linux" ]]; then
            cd oc-*; make cross-build-{{OS}}-{{ARCH}} OS_GIT_VERSION={{.OC_VERSION}} SHELL=/bin/bash
            mv _output/bin/{{OS}}_{{ARCH}}/oc {{.BIN}}/oc
          elif [[ "{{OS}}" == "darwin" ]]; then
            brew install openshift-cli
          fi
        fi
    silent: true

  kind:install:
    run: once
    desc: Downloads and Installs 'kind'
    deps: [configure, bin:install]
    vars:
      KIND_VERSION: "v0.20.0"
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ ! $(command -v kind ) ]]; then
          if [[ "{{OS}}" == "linux" ]]; then
            curl -sSLo {{.BIN}}/kind https://kind.sigs.k8s.io/dl/{{.KIND_VERSION}}/kind-{{OS}}-{{ARCH}} && chmod 0750 {{.BIN}}/kind
          elif [[ "{{OS}}" == "darwin" ]]; then
            brew install kind
          fi
        fi
    silent: true

  neovim:download:
    run: once
    desc: Downloads 'neovim' from GitHub releases and extracts its contents to {{.LOCAL_TMP}}
    deps: [configure]
    vars:
      NVIM_VERSION: "0.10.0"
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - curl -sSLf https://github.com/neovim/neovim/releases/download/v{{.NVIM_VERSION}}/nvim-linux64.tar.gz | tar -zx
    silent: true

  neovim:install:
    run: once
    desc: Installs 'neovim'
    deps: [configure, neovim:download, bin:install]
    vars:
      NVIM_VERSION: "0.10.0"
    dir: "{{.LOCAL_TMP}}"
    cmds:
      - >
        if [[ ! $(command -v nvim ) ]]; then
          if [[ "{{OS}}" == "linux" ]]; then
            mv nvim-linux64 {{.BIN}}/
            ln -s {{.BIN}}/nvim-linux64/bin/nvim {{.BIN}}/nvim
            chmod 0755 {{.BIN}}/nvim-linux64/bin/nvim
          elif [[ "{{OS}}" == "darwin" ]]; then
            brew install neovim
          fi
        fi
    silent: true
  cleanup:
    run: once
    desc: Cleans out the temporary install directory at {{.LOCAL_TMP}}
    deps: [configure]
    cmds:
      - rm -rf {{.LOCAL_TMP}}/*
      - rmdir {{.LOCAL_TMP}}
    silent: false
